# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
      sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test